### ISSUE TITLE
Sample swagger.json? or provide example project?

### ISSUE THREAD

**Issue by yaochen** [marklawlor/jaws-swagger#14]
Hi,

Could you provide a sample json?

I tried using a swagger sample(petstore simpl) and downloaded the api as json and tried to init using that json; I get the following:

```
yaos-imac:jaws-swagger yao$ ./bin/jaws-swagger init swagger.json
Initializing jaws project from swagger.json
Error running command ./node_modules/.bin/jaws module create pets-{id} get --method GET --path /api/pets/{id}

/Users/yao/jaws-swagger/lib/commands/init.js:64
        throw stderr;
        ^
{ [JawsError: Must be in a JAWS project]
  name: 'JawsError',
  message: 'Must be in a JAWS project',
  messageId: 12 }
```

If this is not the correct way, please advise.

**Comment by marklawlor** [comment]
Hi @yaochen I'd hold off using this tool for a bit, its currently under a total rewrite to support JAWS v1.4. 

Projects your create with the current version are going to be incompatible in 1-2weeks. I'll update the readme with more info
